# Exercícios de Pandas

Baseado nos tópicos do curso **Pandas** do Kaggle Learn. Não depende de internet nem de datasets externos — os dados são criados aqui mesmo.

Tente resolver cada exercício antes de olhar o gabarito em `exercicios_pandas_solucoes.ipynb`.

Rode a célula abaixo primeiro (cria os dados usados no resto do notebook).

In [5]:
import pandas as pd
import numpy as np

vendas = pd.DataFrame({
    "produto": ["Notebook", "Mouse", "Teclado", "Monitor", "Cadeira",
                "Mesa", "Headset", "Webcam", "Impressora", "Roteador"],
    "categoria": ["Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos", "Móveis",
                  "Móveis", "Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos"],
    "preco": [3500, 80, 150, 1200, 450, 600, 200, 120, 900, 250],
    "quantidade": [10, 50, 30, 15, 8, 5, 25, 40, 12, 20]
})
vendas

      produto    categoria  preco  quantidade
0    Notebook  Eletrônicos   3500          10
1       Mouse  Eletrônicos     80          50
2     Teclado  Eletrônicos    150          30
3     Monitor  Eletrônicos   1200          15
4     Cadeira       Móveis    450           8
5        Mesa       Móveis    600           5
6     Headset  Eletrônicos    200          25
7      Webcam  Eletrônicos    120          40
8  Impressora  Eletrônicos    900          12
9    Roteador  Eletrônicos    250          20

## 1. Creating, Reading and Writing

**1.1** Crie um `DataFrame` chamado `alunos` com colunas `nome`, `nota1`, `nota2` para 5 alunos inventados.

**1.2** Crie uma `Series` chamada `precos_frutas` com índice sendo nomes de frutas (ex: "maçã", "banana", "uva") e valores sendo os preços.

**1.3** Salve o `vendas` em um arquivo `vendas.csv` (use `to_csv`, com `index=False`) e depois leia esse arquivo de volta em uma variável `vendas_lido` (use `read_csv`).

In [3]:
# 1.1
alunos = pd.DataFrame({ 
    "nome": ["Alice", "Bob", "Charlie", "David", "Eva"], 
    "nota1": [8.5, 7.0, 9.0, 6.5, 8.0], "nota2": [9.0, 6.5, 8.5, 7.0, 9.5] })

In [5]:
# 1.2

precos_frutas = pd.DataFrame({
    "fruta": ["Maçã", "Banana", "uva"], "valores": [3.5, 2.0, 4.0]})
print(precos_frutas)

    fruta  valores
0    Maçã      3.5
1  Banana      2.0
2     uva      4.0

In [8]:
# 1.3
vendas.to_csv("vendas.csv", index=False)
vendas_lido= pd.read_csv("vendas.csv")
vendas_lido

      produto    categoria  preco  quantidade
0    Notebook  Eletrônicos   3500          10
1       Mouse  Eletrônicos     80          50
2     Teclado  Eletrônicos    150          30
3     Monitor  Eletrônicos   1200          15
4     Cadeira       Móveis    450           8
5        Mesa       Móveis    600           5
6     Headset  Eletrônicos    200          25
7      Webcam  Eletrônicos    120          40
8  Impressora  Eletrônicos    900          12
9    Roteador  Eletrônicos    250          20

## 2. Indexing, Selecting & Assigning

Use o DataFrame `vendas` criado no início.

**2.1** Selecione apenas a coluna `produto` (como Series).

**2.2** Selecione as 3 primeiras linhas usando `iloc`.

**2.3** Selecione a linha cujo índice é 4 usando `loc`.

**2.4** Selecione apenas os produtos com `preco` maior que 300.

**2.5** Selecione os produtos da categoria "Eletrônicos" **e** com `quantidade` maior que 20 (use `&`).

**2.6** Crie uma nova coluna `valor_total` = `preco` * `quantidade`.

In [13]:
# 2.1
vendas_produtos = vendas["produto"]
vendas_produtos

0      Notebook
1         Mouse
2       Teclado
3       Monitor
4       Cadeira
5          Mesa
6       Headset
7        Webcam
8    Impressora
9      Roteador
Name: produto, dtype: str

In [12]:
# 2.2
vendas_linhas = vendas.iloc[0:3]
vendas_linhas

    produto    categoria  preco  quantidade
0  Notebook  Eletrônicos   3500          10
1     Mouse  Eletrônicos     80          50
2   Teclado  Eletrônicos    150          30

In [15]:
# 2.3
vendas_linhas = vendas.loc[4]
vendas_linhas

produto       Cadeira
categoria      Móveis
preco             450
quantidade          8
Name: 4, dtype: object

In [17]:
# 2.4
vendas_produtos = vendas.loc[vendas.preco > 300, "produto"]
vendas_produtos

0      Notebook
3       Monitor
4       Cadeira
5          Mesa
8    Impressora
Name: produto, dtype: str

In [18]:
# 2.5
vendas_eletrônicos = vendas.loc[(vendas.categoria.isin(["Eletrônicos"])) & (vendas.quantidade > 20)]
vendas_eletrônicos

   produto    categoria  preco  quantidade
1    Mouse  Eletrônicos     80          50
2  Teclado  Eletrônicos    150          30
6  Headset  Eletrônicos    200          25
7   Webcam  Eletrônicos    120          40

In [19]:
# 2.6
vendas_nova_coluna = vendas.assign(valor_total = vendas.preco * vendas.quantidade)
vendas_nova_coluna

      produto    categoria  preco  quantidade  valor_total
0    Notebook  Eletrônicos   3500          10        35000
1       Mouse  Eletrônicos     80          50         4000
2     Teclado  Eletrônicos    150          30         4500
3     Monitor  Eletrônicos   1200          15        18000
4     Cadeira       Móveis    450           8         3600
5        Mesa       Móveis    600           5         3000
6     Headset  Eletrônicos    200          25         5000
7      Webcam  Eletrônicos    120          40         4800
8  Impressora  Eletrônicos    900          12        10800
9    Roteador  Eletrônicos    250          20         5000

## 3. Summary Functions and Maps

**3.1** Use `describe()` no DataFrame `vendas` e observe as estatísticas.

**3.2** Calcule a média (`mean`) e a mediana (`median`) da coluna `preco`.

**3.3** Descubra quantas categorias únicas existem na coluna `categoria` (use `unique()` e `value_counts()`).

**3.4** Use `map()` para criar uma coluna `preco_com_desconto` aplicando 10% de desconto sobre `preco`.

**3.5** Use `apply()` com uma função própria para criar uma coluna `faixa`, classificando cada produto como `"barato"` (preco < 200), `"médio"` (200 <= preco < 1000) ou `"caro"` (preco >= 1000).

In [21]:
# 3.1
vendas_descricao = vendas.describe()
vendas_descricao

             preco  quantidade
count    10.000000   10.000000
mean    745.000000   21.500000
std    1035.913446   14.759178
min      80.000000    5.000000
25%     162.500000   10.500000
50%     350.000000   17.500000
75%     825.000000   28.750000
max    3500.000000   50.000000

In [23]:
# 3.2
vendas_media_mediana = vendas["preco"].agg(["mean", "median"])
vendas_media_mediana

mean      745.0
median    350.0
Name: preco, dtype: float64

In [24]:
# 3.3
vendas_unicas = vendas["categoria"].unique().value_counts()
vendas_unicas

Eletrônicos    1
Móveis         1
Name: count, dtype: int64

In [26]:
# 3.4
preco_com_desconto = vendas.assign(preco_desconto=vendas["preco"].map(lambda p: p * 0.9))
preco_com_desconto

      produto    categoria  preco  quantidade  preco_desconto
0    Notebook  Eletrônicos   3500          10          3150.0
1       Mouse  Eletrônicos     80          50            72.0
2     Teclado  Eletrônicos    150          30           135.0
3     Monitor  Eletrônicos   1200          15          1080.0
4     Cadeira       Móveis    450           8           405.0
5        Mesa       Móveis    600           5           540.0
6     Headset  Eletrônicos    200          25           180.0
7      Webcam  Eletrônicos    120          40           108.0
8  Impressora  Eletrônicos    900          12           810.0
9    Roteador  Eletrônicos    250          20           225.0

In [28]:
# 3.5
def classificar_faixa(preco):
    if preco < 200:
        return "barato"
    elif preco < 1000:
        return "médio"
    else:
        return "caro"

vendas["faixa"] = vendas["preco"].apply(classificar_faixa)
vendas

      produto    categoria  preco  quantidade   faixa
0    Notebook  Eletrônicos   3500          10    caro
1       Mouse  Eletrônicos     80          50  barato
2     Teclado  Eletrônicos    150          30  barato
3     Monitor  Eletrônicos   1200          15    caro
4     Cadeira       Móveis    450           8   médio
5        Mesa       Móveis    600           5   médio
6     Headset  Eletrônicos    200          25   médio
7      Webcam  Eletrônicos    120          40  barato
8  Impressora  Eletrônicos    900          12   médio
9    Roteador  Eletrônicos    250          20   médio

## 4. Grouping and Sorting

**4.1** Agrupe `vendas` por `categoria` e calcule a soma de `quantidade` em cada grupo (`groupby` + `sum`).

**4.2** Agrupe por `categoria` e calcule, ao mesmo tempo, o preço médio e o total de produtos em cada grupo (use `agg` com um dicionário, ex: `{"preco": "mean", "produto": "count"}`).

**4.3** Ordene `vendas` pela coluna `preco` do maior para o menor (`sort_values`).

**4.4** Ordene o resultado do exercício 4.1 pelo índice (nome da categoria), usando `sort_index`.

In [8]:
# 4.1
vendas.groupby("categoria")["quantidade"].sum()
vendas

      produto    categoria  preco  quantidade
0    Notebook  Eletrônicos   3500          10
1       Mouse  Eletrônicos     80          50
2     Teclado  Eletrônicos    150          30
3     Monitor  Eletrônicos   1200          15
4     Cadeira       Móveis    450           8
5        Mesa       Móveis    600           5
6     Headset  Eletrônicos    200          25
7      Webcam  Eletrônicos    120          40
8  Impressora  Eletrônicos    900          12
9    Roteador  Eletrônicos    250          20

In [7]:
# 4.2
vendas.groupby("categoria").agg({"preco": "mean", "produto": "count"})

             preco  produto
categoria
Eletrônicos  800.0        8
Móveis       525.0        2

In [15]:
# 4.3
vendas.sort_values(by = "preco", ascending= False)
vendas

      produto    categoria  preco  quantidade
0    Notebook  Eletrônicos   3500          10
1       Mouse  Eletrônicos     80          50
2     Teclado  Eletrônicos    150          30
3     Monitor  Eletrônicos   1200          15
4     Cadeira       Móveis    450           8
5        Mesa       Móveis    600           5
6     Headset  Eletrônicos    200          25
7      Webcam  Eletrônicos    120          40
8  Impressora  Eletrônicos    900          12
9    Roteador  Eletrônicos    250          20

In [16]:
# 4.4
vendas.groupby("categoria")["quantidade"].sum().sort_index

<bound method Series.sort_index of categoria
Eletrônicos    202
Móveis          13
Name: quantidade, dtype: int64>

## 5. Data Types and Missing Values

**5.1** Crie uma cópia de `vendas` chamada `vendas_com_nulos` e defina o `preco` das linhas de índice 2 e 5 como `np.nan`.

**5.2** Verifique quantos valores nulos existem em cada coluna de `vendas_com_nulos` (use `isnull().sum()`).

**5.3** Preencha os valores nulos de `preco` com a média da coluna (use `fillna`).

**5.4** Verifique o tipo (`dtype`) de cada coluna com `.dtypes`, depois converta a coluna `quantidade` para `float` usando `astype`.

In [17]:
# 5.1
vendas_com_nulos = vendas.copy()
vendas_com_nulos.loc[[2, 5], "preco"] = np.nan
vendas_com_nulos

      produto    categoria   preco  quantidade
0    Notebook  Eletrônicos  3500.0          10
1       Mouse  Eletrônicos    80.0          50
2     Teclado  Eletrônicos     NaN          30
3     Monitor  Eletrônicos  1200.0          15
4     Cadeira       Móveis   450.0           8
5        Mesa       Móveis     NaN           5
6     Headset  Eletrônicos   200.0          25
7      Webcam  Eletrônicos   120.0          40
8  Impressora  Eletrônicos   900.0          12
9    Roteador  Eletrônicos   250.0          20

In [20]:
# 5.2
vendas_com_nulos.isnull().sum()

produto       0
categoria     0
preco         2
quantidade    0
dtype: int64

In [24]:
# 5.3
media_preco = vendas_com_nulos["preco"].mean()
vendas_com_nulos["preco"] = vendas_com_nulos["preco"].fillna(media_preco)
vendas_com_nulos

      produto    categoria   preco  quantidade
0    Notebook  Eletrônicos  3500.0          10
1       Mouse  Eletrônicos    80.0          50
2     Teclado  Eletrônicos   837.5          30
3     Monitor  Eletrônicos  1200.0          15
4     Cadeira       Móveis   450.0           8
5        Mesa       Móveis   837.5           5
6     Headset  Eletrônicos   200.0          25
7      Webcam  Eletrônicos   120.0          40
8  Impressora  Eletrônicos   900.0          12
9    Roteador  Eletrônicos   250.0          20

In [25]:
# 5.4
print(vendas.dtypes)
vendas["quantidadde"] = vendas["quantidade"].astype(float)
vendas.dtypes

produto         str
categoria       str
preco         int64
quantidade    int64
dtype: object

produto            str
categoria          str
preco            int64
quantidade       int64
quantidadde    float64
dtype: object

## 6. Renaming and Combining

**6.1** Renomeie a coluna `preco` para `preco_unitario` em uma cópia de `vendas` (use `rename`).

**6.2** Renomeie o nome do índice do DataFrame para `"id_venda"` (use `rename_axis`).

**6.3** Crie um segundo DataFrame `vendas_2` com mais 3 produtos (mesmas colunas de `vendas`) e junte os dois em um só, usando `pd.concat`.

**6.4** Crie um DataFrame `estoque` com colunas `produto` e `fornecedor` para alguns dos produtos de `vendas`, e junte com `vendas` usando `merge` (ligando pela coluna `produto`).

In [26]:
# 6.1
renomeando_preco = vendas.copy()
renomeando_preco = renomeando_preco.rename(columns={"preco": "preco_unitario"})
renomeando_preco

      produto    categoria  preco_unitario  quantidade  quantidadde
0    Notebook  Eletrônicos            3500          10         10.0
1       Mouse  Eletrônicos              80          50         50.0
2     Teclado  Eletrônicos             150          30         30.0
3     Monitor  Eletrônicos            1200          15         15.0
4     Cadeira       Móveis             450           8          8.0
5        Mesa       Móveis             600           5          5.0
6     Headset  Eletrônicos             200          25         25.0
7      Webcam  Eletrônicos             120          40         40.0
8  Impressora  Eletrônicos             900          12         12.0
9    Roteador  Eletrônicos             250          20         20.0

In [27]:
# 6.2
renomeando_vendas = vendas.rename_axis(index= "id_venda")
renomeando_vendas

             produto    categoria  preco  quantidade  quantidadde
id_venda
0           Notebook  Eletrônicos   3500          10         10.0
1              Mouse  Eletrônicos     80          50         50.0
2            Teclado  Eletrônicos    150          30         30.0
3            Monitor  Eletrônicos   1200          15         15.0
4            Cadeira       Móveis    450           8          8.0
5               Mesa       Móveis    600           5          5.0
6            Headset  Eletrônicos    200          25         25.0
7             Webcam  Eletrônicos    120          40         40.0
8         Impressora  Eletrônicos    900          12         12.0
9           Roteador  Eletrônicos    250          20         20.0

In [38]:
# 6.3
vendas_p2 = pd.DataFrame({
    "produto": ["Caixa de Som", "Pendrive", "HD Externo"],
    "categoria": ["Eletrônicos", "Eletrônicos", "Eletrônicos"],
    "preco": [150, 800, 1200],
    "quantidade": [15, 10, 5]
})
vendas_completo = pd.concat([vendas[["produto", "categoria", "preco", "quantidade"]], vendas_p2], ignore_index=True)
vendas_completo

         produto    categoria  preco  quantidade
0       Notebook  Eletrônicos   3500          10
1          Mouse  Eletrônicos     80          50
2        Teclado  Eletrônicos    150          30
3        Monitor  Eletrônicos   1200          15
4        Cadeira       Móveis    450           8
5           Mesa       Móveis    600           5
6        Headset  Eletrônicos    200          25
7         Webcam  Eletrônicos    120          40
8     Impressora  Eletrônicos    900          12
9       Roteador  Eletrônicos    250          20
10  Caixa de Som  Eletrônicos    150          15
11      Pendrive  Eletrônicos    800          10
12    HD Externo  Eletrônicos   1200           5

In [39]:
# 6.4
estoque = pd.DataFrame({
    "produto": ["Notebook", "Mouse", "Teclado", "Monitor"],
    "fornecedor": ["TechCorp", "TechCorp", "PeriféricosSA", "TechCorp"]
})
vendas.merge(estoque, on="produto")

    produto    categoria  preco  quantidade  quantidadde     fornecedor
0  Notebook  Eletrônicos   3500          10         10.0       TechCorp
1     Mouse  Eletrônicos     80          50         50.0       TechCorp
2   Teclado  Eletrônicos    150          30         30.0  PeriféricosSA
3   Monitor  Eletrônicos   1200          15         15.0       TechCorp